# Generated by Django 2.2.1 on 2019-05-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date', '-created_date'], 'permissions': [('publish_post', 'Can publish a draft post'), ('view_draft_posts', 'Can view draft posts')]},
        ),
    ]
